name: Package Application with Pyinstaller

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: nab138/pyinstaller-action-linux@tkinter
      with:
        path: .
        tkinter: true

    - uses: actions/upload-artifact@v2
      with:
        name: altserver-gui
        path: dist/
